Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, NumberRange

class Register(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=3, max=30)], 
    render_kw={'class':"form-control", 'placeholder':"Name"})

    age = IntegerField('Age', validators=[DataRequired(), NumberRange(min=0, max=99)], 
    render_kw={'class':"form-control", 'placeholder':"Age"})

    email = StringField('Email', validators=[DataRequired(), Email()],
    render_kw={'class':"form-control", 'placeholder':"Email"})

    password = StringField('Password', validators=[DataRequired()],
    render_kw={'class':"form-control", 'placeholder':"Password"})

    confirm_password = StringField('Confirm Password', validators=[DataRequired(), EqualTo('password')],
    render_kw={'class':"form-control", 'placeholder':"Confirm Passord"})

    submit = SubmitField('Sign Up')

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/__init__.py
from flask import Flask

app = Flask(__name__)
app.config['SECRET_KEY'] = 'sdf55sd411415a8554a2d1'

from studyeasy.main.routes import main 
from studyeasy.blog.routes import blog

app.register_blueprint(main)
app.register_blueprint(blog)

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/blog/routes.py
from flask import render_template, redirect, url_for, Blueprint
from studyeasy.blog.forms import Register

blog = Blueprint('blog', __name__)

@blog.route('/register', methods=('GET', 'POST'))
def register():
    form = Register()
    if form.validate_on_submit():
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

@blog.route('/posts')
def posts():
    return render_template('posts.html', title='Posts')


@blog.route('/add_post')
def add_post():
    return render_template('add_post.html', title='Add post')

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/main/routes.py
from flask import render_template, Blueprint


main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Homepage')


@main.route('/about')
def about():
    return render_template('about.html', title='About')

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/about.html
{% extends 'layout.html'  %}

{% block contents %}


    <p> Content of about page</p>


    
{% endblock contents%}

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/add_post.html
{% extends 'layout.html'  %}

{% block contents %}


    <p> Add post form</p>


    
{% endblock contents%}

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/home.html
{% extends 'layout.html'  %}

{% block contents %}
  

<p> This is homepge </p>


{% endblock %}

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
    {% if title == null %}
        WebAPP
    {% else %}
        {{title}}
    {% endif %}

   </title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">





  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/clean-blog.min.css') }}" rel="stylesheet">

</head>

<body>
     <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">WebApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>




            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>

            <a class="nav-item nav-link" href="{{ url_for('blog.register') }}">Register</a>
           
            
          </div>
        </div>
      </nav>

    <div class="container">
        {% block contents %}
        {% endblock %}
    </div>


 <!-- Footer -->
 <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/StudyEasyOrg">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.facebook.com/studyeasy.org/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ url_for('static', filename='js/clean-blog.min.js') }}"></script>

</body>

</html>

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/posts.html
{% extends 'layout.html'  %}

{% block contents %}


    <p>List pf posts</p>


    
{% endblock contents%}

Section 33 - Flask App with ML model Sample/S32L17 - Flask Blueprint design pattern overview/studyeasy/templates/register.html
{% extends 'layout.html' %}

{% block contents %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h3>Registration form<h3></h3>
            <form method="POST" action="">
                {{ form.csrf_token }}

                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        {{ form.name.label }} {{ form.name() }} <br />
                        {% if form.name.errors %}
                        {% for error in form.name.errors %}
                        <div class='text-danger'>{{ form.name.label }} {{error}} </div> <br />
                        {% endfor %}
                        {% endif %}

                    </div>
                </div>



                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        {{ form.age.label }} {{ form.age() }} <br />
                        {% if form.age.errors %}
                        {% for error in form.age.errors %}
                        <div class='text-danger'>{{ form.age.label }} {{error}} </div> <br />
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>



                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        {{ form.email.label }} {{ form.email() }} <br />
                        {% if form.email.errors %}
                        {% for error in form.email.errors %}
                        <div class='text-danger'> {{ form.email.label }} {{error}} </div> <br />
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>



                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        {{ form.password.label }} {{ form.password() }} <br />

                    </div>
                </div>
                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        {{ form.confirm_password.label }} {{ form.confirm_password() }} <br />
                        {% if form.confirm_password.errors %}
                        {% for error in form.confirm_password.errors %}
                        <div class='text-danger'>{{ form.confirm_password.label }} {{error}}</div> <br />
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>


                <div id="success"></div>
                {{ form.submit() }}

            </form>
        </h3>
    </div>

    {% endblock contents%}